### PR TITLE
Fix for issue #449 Match "Requested Attributes" from metadata to ARP

### PR DESCRIPTION
**Pull request by relaxnow**
screen shot 2015-05-13 at 14 09 22

See #449

### CODE REVIEW

**Comment by relaxnow** [comment]
Tried to refactor out our dependence on the crappy SimpleSAMLphp SAMLParser so we'd have more flexibility (and easier migration away from SSP as a framework) in https://github.com/janus-ssp/janus/tree/feature/refactor-import but that quickly turned out to be too ambitious for the remaining time.

**Comment by thijskh** [comment]
Just to confirm: this does not have the ability to "not apply this change"?

**Comment by relaxnow** [comment]
@thijskh nope, you can't skip it.

**Comment by relaxnow** [comment]
Just added a comment on https://github.com/janus-ssp/janus/issues/449#issuecomment-101652254 with the limitations of the current solution.

**Comment by thijskh** [comment]
:+1:

**Pull request merged**
