### PR TITLE
Getting rid of a bunch of deprecation notices

### PR DESCRIPTION
**Pull request by tvdijen**
Not sure how to properly test this, but I'm running with these dependencies for quite a while now and haven't run into any issues yet.

### CODE REVIEW

**Comment by tvdijen** [comment]
Ha, and then I ran into an issue on a new install while running bin/migrate.sh:
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
  Circular reference detected for service "security.context", path: "security.context".

**Comment by thijskh** [comment]
So I think we won't be merging this?

**Comment by tvdijen** [comment]
Auch, I kinda forgot about this...

It looks like it has something to do with the way 'stuff' is being injected:
http://stackoverflow.com/questions/24139115/circular-reference-detected-for-service-security-context

This obviously needs some work and I'm not sure if I'm up for the job, since I'm not really a developer. I will however investigate this some more, hopefully this week.

**Comment by tvdijen** [comment]
From the Symfony 2.7 upgrade notice:
feature #13323 [Security] removed usage of the deprecated SecurityContextInterface

That leaves us with 2.6 for now, but at least we got rid of a ton of deprecation notices!

**Pull request merged**
